version: '3.9'

#### NETWORKS ####

networks:
  elevator-network:
    external: false

#### SERVICES ####

services:
  client:
    container_name: elevator-client
    build: ./client
    ports:
      - 3000:3000
    networks:
      - elevator-network

  server:
    container_name: elevator-server
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - CLIENT_ADDRESS={CLIENT_ADDRESS}
    ports:
      - 8080:8080
    networks:
      - elevator-network