version: '3.9'

#### NETWORKS ####

networks:
  elevator-network:
    external: false

#### SERVICES ####

services:
  server:
    container_name: elevator-server
    build: ./server
    ports:
      - 8082:8080
    networks:
      - elevator-network